name: 'IndexNow'
on:
  push:
    branches:
      - main
jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: indexnow-action
        uses: bojieyang/indexnow-action@v3
        with:
          sitemap-location: 'https://mooncabincollective.com/sitemap.xml'
          key: ${{ secrets.INDEXNOW_KEY }}
